name: tfenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.9.9=h06a4308_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.7.29=hbc23b4c_3
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.19=hee96239_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.4=h6a678d5_0
  - numactl=2.0.19=hee96239_0
  - openssl=3.4.1=h7b32b05_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.2=h2c6b66d_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - absl-py==0.15.0
      - astunparse==1.6.3
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - clang==5.0
      - flatbuffers==1.12
      - gast==0.4.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h5py==3.1.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - keras==2.6.0
      - keras-preprocessing==1.1.2
      - markdown==3.7
      - markupsafe==2.1.5
      - numpy==1.19.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==3.20.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scipy==1.10.1
      - six==1.15.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorflow-estimator==2.6.0
      - tensorflow-gpu==2.6.0
      - termcolor==1.1.0
      - typing-extensions==3.7.4.3
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - wrapt==1.12.1
      - zipp==3.20.2
prefix: /home/rc/anaconda3/envs/tfenv
